---
- name: Kafka Provisioning
  hosts: all
  remote_user: root
  gather_facts: false
  tags: kafka_connect
  tasks:
    - name: apt-get update and upgrade
      apt:
        update_cache: yes
        upgrade: full
        force_apt_get: yes
    - name: install java and docker
      apt:
        name: openjdk-11-jdk, jq, docker, docker-compose, python3, s3fs, python3-pip
        state: latest
        force_apt_get: yes
    - name: Create spooldir directories
      shell:
        cmd: mkdir /var/spooldir/ && chown ubuntu:ubuntu /var/spooldir/
    - name: copy AWS credentials to mount S3 bucket
      copy:
        src: passwd-s3fs
        dest: /etc/passwd-s3fs
        mode: 640
    - name: mount s3fs
      shell:
        cmd: s3fs -o allow_other -o umask=0000 -o rw ${{your_s3_bucket_nme}} /var/spooldir/
    - name: Copying connect.properties
      copy:
        src: connect.properties
        dest: /home/ubuntu/connect.properties
    - name: Copying create_docker_compose_dot_yaml.py
      copy:
        src: create_docker_compose_dot_yaml.py
        dest: /home/ubuntu/create_docker_compose_dot_yaml.py
    - name: Copying yak_shaving.conf config file
      copy:
        src: yak_shaving.conf
        dest: /home/ubuntu/yak_shaving.conf
    - name: Installing Python Modules
      pip:
        name:
          - ruamel.yaml
    - name: Creating docker-compose.yml file
      script: create_docker_compose_dot_yaml.py
      args:
        executable: python3
    - name: Adding user ubuntu to Docker group
      ansible.builtin.user:
        name: ubuntu
        append: true
        groups: docker
    # TODO: add a step here to install connectors using confluent hub
    - name: Starting Docker
      shell:
        cmd: docker-compose up -d

